Function SetISOFileName

     !insertmacro SetISOFileNames "--- Ubuntu 32/64 Bit ---" "" "" "" "" ""
	 !insertmacro SetISOFileNames "" "" "" "" "" "" 
	 
  !insertmacro SetISOFileNames "Ubuntu" "ubuntu*desktop*.iso" "http://www.ubuntu.com/download/desktop" "casper" "http://ubuntu.com/desktop" "Ubuntu"   
  !insertmacro SetISOFileNames "Edubuntu" "edubuntu*dvd*.iso" "http://cdimage.ubuntu.com/edubuntu/releases/trusty/release/edubuntu-14.04.4-dvd-i386.iso" "casper" "http://edubuntu.org/" "Edubuntu" 
  !insertmacro SetISOFileNames "Kubuntu" "kubuntu*desktop*.iso" "http://kubuntu.org/getkubuntu/" "casper" "http://kubuntu.org" "Kubuntu"  
  !insertmacro SetISOFileNames "Lubuntu" "lubuntu*desktop*.iso" "http://cdimage.ubuntu.com/lubuntu/releases/15.10/release/lubuntu-15.10-desktop-i386.iso" "casper" "http://lubuntu.org" "Lubuntu"  
  !insertmacro SetISOFileNames "Xubuntu" "xubuntu*desktop*.iso" "http://cdimage.ubuntu.com/xubuntu/releases/15.10/release/xubuntu-15.10-desktop-i386.iso" "casper" "http://xubuntu.org" "Xubuntu"  
  !insertmacro SetISOFileNames "Mythbuntu" "mythbuntu*desktop*.iso" "http://cdimage.ubuntu.com/mythbuntu/releases/14.04.4/release/mythbuntu-14.04.4-desktop-i386.iso" "casper" "http://mythbuntu.org" "Mythbuntu" 
  !insertmacro SetISOFileNames "Blackbuntu" "bb*.iso" "http://sourceforge.net/projects/blackbuntu/files/latest/download" "casper" "http://blackbuntu.com" "Blackbuntu"
  !insertmacro SetISOFileNames "Ubuntu Mate" "ubuntu-mate*.iso" "http://cdimage.ubuntu.com/ubuntu-mate/releases/15.10/release/ubuntu-mate-15.10-desktop-i386.iso" "casper" "https://ubuntu-mate.org" "Ubuntu Mate"   
  !insertmacro SetISOFileNames "Ubuntu Server Installer" "ubuntu*server*.iso" "http://releases.ubuntu.com/14.04/ubuntu-14.04.4-server-i386.iso" "no" "http://ubuntu.com/server" "Ubuntu Server"   

     !insertmacro SetISOFileNames "" "" "" "" "" ""
     !insertmacro SetISOFileNames "--- Linux Mint 32/64 Bit ---" "" "" "" "" ""
	 !insertmacro SetISOFileNames "" "" "" "" "" "" 

  !insertmacro SetISOFileNames "Linux Mint" "linuxmint*.iso" "http://mirrors.kernel.org/linuxmint/stable/17.3/" "casper" "http://www.linuxmint.com" "Linux Mint"	 
 
     !insertmacro SetISOFileNames "" "" "" "" "" ""
     !insertmacro SetISOFileNames "--- Debian Live/Netinst 32/64 Bit ---" "" "" "" "" ""
	 !insertmacro SetISOFileNames "" "" "" "" "" "" 
	 
  !insertmacro SetISOFileNames "Debian Live" "debian-live*.iso" "http://cdimage.debian.org/debian-cd/current-live/i386/iso-hybrid/" "no" "http://live.debian.net" "Debian Live"	 
  !insertmacro SetISOFileNames "Debian Netinst" "debian*netinst.iso" "" "no" "http://www.debian.org/CD/netinst/" "Debian Network Install"
 
     !insertmacro SetISOFileNames "" "" "" "" "" "" 
     !insertmacro SetISOFileNames "--- Fedora 32/64 Bit ---" "" "" "" "" ""
	 !insertmacro SetISOFileNames "" "" "" "" "" ""

  !insertmacro SetISOFileNames "Fedora Live Desktop" "Fedora*Live*.iso" "https://getfedora.org/en/workstation/download/" "no" "http://fedoraproject.org" "Fedora"  

     !insertmacro SetISOFileNames "" "" "" "" "" "" 
     !insertmacro SetISOFileNames "--- OpenSUSE Live 32/64 Bit ---" "" "" "" "" ""
	 !insertmacro SetISOFileNames "" "" "" "" "" "" 

  !insertmacro SetISOFileNames "OpenSUSE 32bit" "openSUSE*86.iso" "http://suse.mirrors.tds.net/pub/opensuse/distribution/13.2/iso/openSUSE-13.2-GNOME-Live-i686.iso" "no" "http://software.opensuse.org" "OpenSUSE"    
  !insertmacro SetISOFileNames "OpenSUSE 64bit" "openSUSE*64.iso" "http://suse.mirrors.tds.net/pub/opensuse/distribution/13.2/iso/openSUSE-13.2-GNOME-Live-x86_64.iso" "no" "http://software.opensuse.org" "OpenSUSE"    

     !insertmacro SetISOFileNames "" "" "" "" "" ""
     !insertmacro SetISOFileNames "--- Puppy Linux Based ---" "" "" "" "" ""
	 !insertmacro SetISOFileNames "" "" "" "" "" ""  
	 
  !insertmacro SetISOFileNames "Fatdog64" "Fatdog64*.iso" "http://distro.ibiblio.org/fatdog/iso/Fatdog64-702.iso" "no" "http://www.puppylinuxforum.org/thread-180.html" "Fatdog64"
  !insertmacro SetISOFileNames "Lighthouse Puppy" "LighthousePup*.iso" "http://www.lhpup.org/release/lhp502/LighthousePup-5.02-G.iso" "no" "http://www.lhpup.org" "Lighthouse Puppy"
  !insertmacro SetISOFileNames "Lucid Puppy" "lupu*.iso" "http://distro.ibiblio.org/pub/linux/distributions/puppylinux/puppy-5.2.8/lupu-528.005.iso" "no" "http://www.puppylinux.org" "Puppy"
  !insertmacro SetISOFileNames "Puppy Arcade" "puppy-arcade*.iso" "http://downloads.scottjarvis.com/grab.php?f=puppy-arcade-10.iso" "no" "http://scottjarvis.com/page105.htm" "Puppy Arcade"
  !insertmacro SetISOFileNames "Puppy 4.3.1" "pup-431.iso" "http://ftp.nluug.nl/ftp/pub/os/Linux/distr/puppylinux/puppy-4.3.1/pup-431.iso" "no" "http://www.puppylinux.org" "Puppy"
  !insertmacro SetISOFileNames "Precise Puppy" "precise*.iso" "http://distro.ibiblio.org/quirky/precise-5.7.1/precise-5.7.1.iso" "no" "http://bkhome.org/blog/?viewDetailed=03063" "Precise Puppy"  
  !insertmacro SetISOFileNames "Racy Puppy" "racy*.iso" "http://distro.ibiblio.org/quirky/racy-5.5/racy-5.5.iso" "no" "http://puppylinux.org/main/New%20Racy%20Puppy.htm" "Racy Puppy" 
  !insertmacro SetISOFileNames "Slacko Puppy" "slacko*.iso" "http://www.smokey01.com/01micko/slacko/slacko-5.4/slacko-5.4-firefox-4g.iso" "no" "http://puppylinux.org/wikka/Puppy53" "Slacko Puppy"  
  !insertmacro SetISOFileNames "Wary Puppy" "wary*.iso" "http://distro.ibiblio.org/quirky/wary-5.5/wary-5.5.iso" "no" "http://puppylinux.org/main/Long-Term-Supported%20WaryPuppy.htm" "Wary Puppy"	 

     !insertmacro SetISOFileNames "" "" "" "" "" ""
     !insertmacro SetISOFileNames "--- Linux Distros for Kids ---" "" "" "" "" ""
	 !insertmacro SetISOFileNames "" "" "" "" "" ""     
	 
  !insertmacro SetISOFileNames "DouDouLinux" "doudoulinux-gondwana*.iso" "http://download.doudoulinux.org/livecd/1.2/doudoulinux-gondwana-1.2-en.iso" "no" "http://download.doudoulinux.org" "DouDouLinux"
  !insertmacro SetISOFileNames "Qimo 4 Kids 2.0" "qimo-2.0-desktop.iso" "http://www2.niux.com.ar/qimo-2.0-desktop.iso" "casper" "http://www.qimo4kids.com" "Qimo 4 Kids"
  !insertmacro SetISOFileNames "Sugar on a Stick" "Fedora-Live-SoaS*.iso" "http://dl.fedoraproject.org/pub/alt/releases/19/Spins/i386/Fedora-Live-SoaS-i686-19-1.iso" "no" "http://wiki.sugarlabs.org" "Sugar"	 
  
     !insertmacro SetISOFileNames "" "" "" "" "" ""
     !insertmacro SetISOFileNames "--- Other Distros Alphabetical ---" "" "" "" "" ""
	 !insertmacro SetISOFileNames "" "" "" "" "" ""  
	 
  !insertmacro SetISOFileNames "Acronis Rescue CD" "AcronisAntimalwareScanCD.iso" "http://download.acronis.com/iso/AcronisAntimalwareScanCD.iso" "no" "http://kb.acronis.com/content/18647" "Acronis Rescue CD" 
  !insertmacro SetISOFileNames "Android" "android*.iso" "http://code.google.com/p/android-x86/downloads/list" "no" "http://android-x86.googlecode.com" "Android x86"
  !insertmacro SetISOFileNames "Antix" "AntiX*.iso" "http://sourceforge.net/projects/antix-linux/files/Final/antiX-13.1/antiX-13.1_386-full.iso/download" "no" "http://antix.mepis.org/index.php?title=Main_Page" "AntiX"
  !insertmacro SetISOFileNames "AOMEI" "amlnx.iso" "http://www.aomeisoftware.com/download/adb/amlnx.iso" "no" "http://www.backup-utility.com/" "AOMEI (Disk Backup)"
  !insertmacro SetISOFileNames "ArchBang" "archBang*.iso" "https://sourceforge.net/projects/archbang/files/latest/download?source=files" "no" "http://archbang.org" "ArchBang"
  ;!insertmacro SetISOFileNames "ArchLinux" "archlinux*.iso" "http://mirror.rackspace.com/archlinux/iso/2016.04.01/archlinux-2016.04.01-dual.iso" "no" "http://www.archlinux.org" "ArchLinux"
  !insertmacro SetISOFileNames "ArtistX" "artistx*.iso" "http://bo.mirror.garr.it/mirrors/artistx/artistx_1.5_live_dvd_iso_15_09_2013.iso" "casper" "http://www.artistx.org" "ArtistX"
  !insertmacro SetISOFileNames "Baltix Linux" "Baltix*.iso" "http://download.vikis.lt/baltix/Baltix-Linux-14.04-desktop-2014-06.iso" "casper" "http://baltix.akl.lt/" "Baltix Linux"
  !insertmacro SetISOFileNames "BCCD" "bccd*.iso" "http://cluster.earlham.edu/bccd-ng/stable/bccd-3.3.0.i386.iso" "no" "http://bccd.net/" "BCCD"
  !insertmacro SetISOFileNames "BlehOS" "BlehOS.i686*.iso" "http://sourceforge.net/projects/blehos/files/latest/download" "no" "http://sourceforge.net/projects/blehos/" "BlehOS"    
  !insertmacro SetISOFileNames "Bodhi" "bodhi*.iso" "http://sourceforge.net/projects/bodhilinux/files/latest/download" "casper" "http://bodhilinux.com" "Bodhi"
  !insertmacro SetISOFileNames "Boot Repair Disk" "boot-repair-disk.iso" "http://sourceforge.net/projects/boot-repair-cd/files/latest/download" "no" "http://sourceforge.net/p/boot-repair-cd/home/Home/" "Boot Repair Disk"
  !insertmacro SetISOFileNames "Carmedia" "carmedia*.iso" "http://ac-services.eu/carmedia/carmedia-stable-12.04.iso" "casper" "" ""   
  !insertmacro SetISOFileNames "CentOS" "CentOS*LiveCD*.iso" "http://mirrors.kernel.org/centos/7/isos/x86_64/CentOS-7-x86_64-LiveCD-1503.iso" "no" "http://www.centos.org" "CentOS"
  !insertmacro SetISOFileNames "Clonezilla" "clonezilla*.iso" "http://sourceforge.net/projects/clonezilla/files/clonezilla_live_stable/2.4.2-10/clonezilla-live-2.4.2-10-amd64.iso/download" "no" "http://clonezilla.org" "Clonezilla"
  !insertmacro SetISOFileNames "Crunchbang" "crunchbang*.iso" "http://crunchbanglinux.org/downloads/" "no" "http://crunchbanglinux.org" "Crunchbang"
  !insertmacro SetISOFileNames "DBAN 2.2.X" "dban-2.2.*_i586.iso" "http://downloads.sourceforge.net/project/dban/dban/dban-2.2.7/dban-2.2.7_i586.iso?use_mirror=autodetect" "no" "http://www.dban.org" "DBAN"
  !insertmacro SetISOFileNames "Deepin Linux" "deepin*.iso" "http://www.linuxdeepin.com/download" "no" "http://www.linuxdeepin.com/" "Deepin"
  !insertmacro SetISOFileNames "DRBL" "drbl-live*.iso" "http://sourceforge.net/projects/drbl/files/drbl_live_stable/2.1.0-12/drbl-live-xfce-2.1.0-12-i686-pae.iso/download" "no" "http://drbl.sourceforge.net" "DRBL"
  !insertmacro SetISOFileNames "Dreamlinux" "Dreamlinux-5*.iso" "http://download.linux-live-cd.org/iso/Dreamlinux/Dreamlinux-5.iso" "no" "http://www.dreamlinux.net" "Dreamlinux"
  !insertmacro SetISOFileNames "DSL 4.4.10" "dsl-4.4.10-embedded.zip" "ftp://distro.ibiblio.org/pub/linux/distributions/damnsmall/current/dsl-4.4.10-embedded.zip" "no" "http://www.damnsmalllinux.org" "Damn Small Linux"
  !insertmacro SetISOFileNames "Dynebolic" "dynebolic*.iso" "http://www.dynebolic.org/download/" "no" "http://dynebolic.org" "Dynebolic"
  !insertmacro SetISOFileNames "EASUS Disk Copy" "DiskCopy.iso" "http://download.easeus.com/free/EaseUS_DiskCopy_Home.exe" "no" "http://www.easeus.com/disk-copy/" "EASUS Disk Copy"
  !insertmacro SetISOFileNames "EasyPeasy" "easypeasy*.iso" "http://sourceforge.net/projects/ubuntu-eee/files/EasyPeasy/EasyPeasy-1.6.iso/download" "casper" "http://www.geteasypeasy.com" "EasyPeasy"
  !insertmacro SetISOFileNames "Elementary OS" "elementaryos*.iso" "http://sourceforge.net/projects/elementaryos/files/latest/download" "casper" "http://elementaryos.org/" "Elementary OS"
  !insertmacro SetISOFileNames "Elementary Unleashed" "eu-dorian-1.1-i386.iso" "http://eu.bondhuta.net/files/dorian/eu-dorian-1.1-i386.iso" "casper" "http://eu.bondhuta.net" "Elementary Unleashed"
  ;Discontinued !insertmacro SetISOFileNames "Feather Linux" "feather*.iso" "ftp://ftp.berlios.de/pub/featherlinux/feather-0.7.5.iso" "no" "http://featherlinux.berlios.de" "Feather Linux "
  !insertmacro SetISOFileNames "Finnix" "finnix*.iso" "http://www.finnix.org/releases/100/finnix-100.iso" "no" "http://www.finnix.org" "Finnix "
  !insertmacro SetISOFileNames "Fuduntu" "Fuduntu*.iso" "http://sourceforge.net/projects/fuduntu/files/Fuduntu-2013.2-x86_64-LiveDVD.iso/download" "no" "http://www.fuduntu.org/" "Fuduntu"  
  ;Discontinued !insertmacro SetISOFileNames "Fusion Linux" "Fusion-Linux-16*.iso" "http://fusionlinux.org/downloads/" "no" "http://www.fusionlinux.org" "Fusion Linux"  
  !insertmacro SetISOFileNames "G4L (Ghost For Linux)" "g4l*.iso" "http://sourceforge.net/projects/g4l/files/latest/download" "no" "http://sourceforge.net/projects/g4l/" "Ghost For Linux"    
  !insertmacro SetISOFileNames "Gamedrift" "GameDrift*.iso" "http://gamedrift.org/Download.html" "casper" "http://gamedrift.org/" "GameDrift"   
  !insertmacro SetISOFileNames "Gentoo" "livedvd*.iso" "http://mirrors.se.kernel.org/gentoo//releases/x86/11.0/livedvd-x86-amd64-32ul-11.0.iso" "no" "http://www.gentoo.org" "Gentoo" 
  !insertmacro SetISOFileNames "GEEXBOX" "geexbox*.iso" "http://www.geexbox.org/wp-content/plugins/download-monitor/download.php?id=geexbox-3.1-x86_64.iso" "casper" "http://www.geexbox.org" "GeexBox"
  !insertmacro SetISOFileNames "gNewSense" "gnewsense-live*.iso" "http://cdimage.gnewsense.org/gnewsense-live-3.0-i386-gnome.iso" "no" "http://www.gnewsense.org/" "gNewSense"
  ;Discontinued !insertmacro SetISOFileNames "gOS 3.1 gadgets" "gos-3.1-gadgets-20081205.iso" "http://gos.psaskiboats.com.au/gos-3.1-gadgets-20081205.iso" "casper" "http://www.thinkgos.com" "gOS"
  !insertmacro SetISOFileNames "GParted" "gparted-live*.iso" "http://sourceforge.net/projects/gparted/files/latest" "no" "http://gparted.sourceforge.net" "gParted"
  !insertmacro SetISOFileNames "GRML" "grml*.iso" "http://grml.org/download/" "no" "http://grml.org" "GRML"
  ;Discontinued !insertmacro SetISOFileNames "Jolicloud" "joli*.iso" "http://www.jolicloud.com/download/jolicloud-iso" "no" "http://www.jolicloud.com" "Jolicloud "
  !insertmacro SetISOFileNames "Kiwi" "kiwilinux*.iso" "http://ftp.astral.ro/mirrors/kiwilinux.org/kiwi-12.08/kiwi-12.08.iso" "casper" "http://kiwilinux.org/kiwi/en/index.html" "Kiwi Linux"
  !insertmacro SetISOFileNames "Korora" "korora*.iso" "http://sourceforge.net/projects/kororaproject/files/latest/download" "no" "https://kororaproject.org/" "Korora"
  !insertmacro SetISOFileNames "KXStudio" "kxstudio*.iso" "http://sourceforge.net/projects/kxstudio/files/latest/download" "casper" "http://kxstudio.sourceforge.net" "KXStudio"  
  ;!insertmacro SetISOFileNames "Leeenux" "leeenux*.iso" "http://www.leeenux-linux.com/Leeenux/leeenux-v4.01.iso" "casper" "http://www.leeenux-linux.com" "Leeenux"
  !insertmacro SetISOFileNames "Liberte" "liberte*.zip" "http://sourceforge.net/projects/liberte/files/2012.3/liberte-2012.3.zip/download" "no" "http://dee.su/liberte" "Liberte"
  !insertmacro SetISOFileNames "LinHES" "LinHES*.iso" "http://www.linhes.org/downloads/Current/" "no" "http://linhes.org" "LinHES"
  !insertmacro SetISOFileNames "Linpus Lite" "linpus-Lite*.iso" "http://update10.linpus.com/Linpus/Linpus-image/Lite2.2/Linpus-Lite-2.2.1.0-x86_64-LiveCD-gdm.iso" "no" "http://www.linpus.com/products_linpuslite.html" "LinPus Lite"
  !insertmacro SetISOFileNames "Linux Lite" "linux-lite*.iso" "http://sourceforge.net/projects/linuxlite/files/latest/download" "casper" "https://www.linuxliteos.com/index.html" "Linux Lite"  
  !insertmacro SetISOFileNames "Linux XP Like" "XP*.iso" "http://sourceforge.net/projects/xplike/files/latest/download" "casper" "http://www.oslike.se/xp-like" "Linux Like XP"
  !insertmacro SetISOFileNames "LPS" "lps*.iso" "http://spi.dod.mil/lipose.htm" "no" "http://spi.dod.mil/index.htm" "LPS"
  !insertmacro SetISOFileNames "LXLE Desktop" "lxle*.iso" "http://www.lxle.net/download" "casper" "http://lxle.net/" "LXLE Desktop" 
  !insertmacro SetISOFileNames "Macbuntu" "macbuntu*.iso" "http://sourceforge.net/projects/macbuntu-iso/files/macbuntu1104.iso/download" "casper" "http://oslike.se" "MacBuntu"
  !insertmacro SetISOFileNames "Manjaro" "Manjaro*.iso" "http://manjaro.org/get-manjaro/" "no" "http://manjaro.org" "Manjaro"
;REVISIT  !insertmacro SetISOFileNames "Mageia Live CD" "Mageia-2-LiveCD*.iso" "http://mirrors.kernel.org/mageia/iso/2/Mageia-2-LiveCD-GNOME-Europe1-Americas-i586-CD/Mageia-2-LiveCD-GNOME-Europe1-Americas-i586-CD.iso" "no" "http://www.mageia.org" "Mageia" 
  !insertmacro SetISOFileNames "Matriux" "Matriux-Krypton*.iso" "http://sourceforge.net/projects/matriux/files/matriux-krypton-v1-2/Matriux-Krypton-v1.2.iso/download" "no" "http://www.matriux.com" "Matriux"
  !insertmacro SetISOFileNames "MCNLive Toronto" "MCNLive-Toronto.iso" "http://ftp.surfnet.nl/os/Linux/distr/mandrakeclubnl/mcnlive/Toronto/MCNLive-Toronto.iso" "no" "http://www.mcnlive.org" "MCNLive"
  !insertmacro SetISOFileNames "Meego" "meego*.img" "http://repo.meego.com/MeeGo/releases/1.2.0/images/meego-netbook-ia32/meego-netbook-ia32-1.2.0.img" "no" "http://meego.com" "Meego"
  !insertmacro SetISOFileNames "mintyMac" "minty*.iso" "http://sourceforge.net/projects/mintymacpremium/files/latest/download" "casper" "http://sourceforge.net/projects/mintymacpremium/" "MintyMac"
  !insertmacro SetISOFileNames "Netrunner" "netrunner*.iso" "http://www.netrunner-os.com/wp-content/plugins/download-monitor/download.php?id=30" "casper" "http://www.netrunner-os.com" "Netrunner"  
  !insertmacro SetISOFileNames "Ophcrack" "ophcrack*iso" "http://sourceforge.net/projects/ophcrack/files/ophcrack-livecd/3.6.0/ophcrack-vista-livecd-3.6.0.iso/download" "no" "http://ophcrack.sourceforge.net" "Ophcrack"
  !insertmacro SetISOFileNames "OSGeo Live" "osgeo-live*.iso" "http://download.osgeo.org/livedvd/release/5.5/osgeo-live-5.5.iso" "casper" "http://live.osgeo.org" "OSGeo Live"  
  !insertmacro SetISOFileNames "PartedMagic" "pmagic*.iso" "http://sourceforge.net/projects/partedmagic/files/?source=navbar" "no" "http://partedmagic.com" "Parted Magic"
  !insertmacro SetISOFileNames "PCLinuxOS" "pclinuxos*.iso" "http://spout.ussg.indiana.edu/linux/pclinuxos/pclinuxos/live-cd/pclinuxos-kde-minime-2014.12.iso" "no" "http://www.pclinuxos.com" "PCLinuxOS"
  !insertmacro SetISOFileNames "Peach OSI" "PeachOSI*.iso" "http://www.peachosi.com/Doors/DonateDownloadPageFluid.html" "casper" "http://www.peachosi.com" "Peach OSI" 
  !insertmacro SetISOFileNames "Pear OS" "pearos*.iso" "http://sourceforge.net/projects/pearlinuxprivat/files/latest/download" "casper" "http://pearlinux.fr" "Pear OS"    
  !insertmacro SetISOFileNames "Peppermint" "Peppermint*.iso" "http://peppermintos.info/32/Peppermint-4-20130611-i386.iso" "casper" "http://peppermintos.com" "Peppermint"
  !insertmacro SetISOFileNames "PING" "PING*.iso" "http://ping.windowsdream.com/ping/Releases/3.00.04/PING-3.00.iso" "no" "http://ping.windowsdream.com/ping.html" "PING"
  !insertmacro SetISOFileNames "Pinguy OS" "Pinguy_OS*.iso" "http://sourceforge.net/projects/pinguy-os/files/Pinguy_OS_12.04_LTS/Pinguy_OS_12.04-shell-i686.iso/download" "casper" "http://pinguy-os.sourceforge.net" "PinguyOS"
  !insertmacro SetISOFileNames "Plasmaactive" "basyskom-plasma-active-two-meego-usb-live.iso" "http://share.basyskom.com/contour//Deployment/MeeGo_x86_USB_Live_and_Install_Archive/basyskom-plasma-active-two-meego-usb-live.iso" "no" "http://plasma-active.org/" "PlasmaActive"
  !insertmacro SetISOFileNames "PLoP Linux" "ploplinux*.iso" "https://www.plop.at/en/ploplinux/downloads/live.html" "no" "http://www.plop.at/en/ploplinux.html" "PLoP"
  !insertmacro SetISOFileNames "Porteus" "porteus*.iso" "http://build.porteus.org/" "no" "https://porteus.org" "Porteus"
  !insertmacro SetISOFileNames "Redo Backup" "redobackup-*.iso" "http://sourceforge.net/projects/redobackup/files/latest" "no" "http://redobackup.org" "RedoBackup"
  !insertmacro SetISOFileNames "Rescatux" "rescatux*.iso" "http://www.supergrubdisk.org/category/download/rescatuxdownloads/" "no" "http://www.supergrubdisk.org/rescatux/" "Rescatux"
  ;Discontinued !insertmacro SetISOFileNames "RIP Linux" "RIPLinuX*.iso" "http://www.tux.org/pub/people/kent-robotti/looplinux/rip/" "no" "http://rip.7bf.de/current/" "RIP Linux "
;REVISIT  !insertmacro SetISOFileNames "ROSA Marathon 2012" "ROSA.2012.MARATHON*.iso" "http://mirror.rosalab.ru/iso/ROSA.Desktop/ROSA.2012.MARATHON/ROSA.2012.MARATHON.FREE.i586.iso" "no" "http://www.rosalab.com" "ROSA"
  !insertmacro SetISOFileNames "Runt Linux" "runt*.zip" "http://runt.mybox.org/runt-5.0.zip" "no" "http://runt.mybox.org" "Runt Linux "
  !insertmacro SetISOFileNames "Sabayon Linux" "Sabayon_Linux*.iso" "ftp://mirror.cs.vt.edu/pub/SabayonLinux/iso/monthly/" "no" "http://www.sabayon.org" "Sabayon Linux"
  ;Discontinued !insertmacro SetISOFileNames "SalineOS" "SalineOS*.iso" "http://www.salineos.com/Downloads/SalineOS-1.7-i686.iso" "no" "http://salineos.com" "SalineOS" 
  !insertmacro SetISOFileNames "Satux" "satux*.iso" "http://repos.satux.org.br/download/satux-3.0.iso" "no" "http://www.satux.org.br/" "Satux"
  !insertmacro SetISOFileNames "Simply MEPIS" "SimplyMEPIS-CD*.iso" "ftp://ftp.ussg.iu.edu/pub/linux/mepis/released/SimplyMEPIS-CD_8.0.15-rel_32.iso" "no" "http://www.mepis.org" "Simply Mepis"
  !insertmacro SetISOFileNames "SLAX" "slax*.iso" "http://www.slax.org/download.php" "no" "http://www.slax.org" "SLAX"
  !insertmacro SetISOFileNames "SliTaZ" "slitaz*.iso" "http://mirror.slitaz.org/iso/4.0/slitaz-4.0.iso" "no" "http://www.slitaz.org/en/" "SliTaZ"
  !insertmacro SetISOFileNames "Sn0wL1nuX" "Sn0wL1nuX*.iso" "http://sourceforge.net/projects/sn0wl1nux/files/latest/download" "casper" "http://sn0wl1nux.forumdoandroid.com" "sn0wl1nux"    
  ;Discontinued !insertmacro SetISOFileNames "SolusOS" "SolusOS*.iso" "http://mirror.layerjet.com/solusos/images/SolusOS-2-A5.iso" "no" "http://solusos.com/" "SolusOS"  
  !insertmacro SetISOFileNames "SolydX" "solydx*.iso" "http://downloads.solydxk.com/" "no" "http://solydxk.com" "SolydX Linux" 
  !insertmacro SetISOFileNames "Sparky Linux" "sparkylinux*.iso" "http://sourceforge.net/projects/sparkylinux/files/latest/download" "no" "http://sparkylinux.org" "Sparky Linux"  
  !insertmacro SetISOFileNames "StartOS" "StartOS*.iso" "http://release.startos.org/release/StartOS-5.1-LiveCD-i686.iso" "casper" "http://www.startos.org/" "StartOS"
  !insertmacro SetISOFileNames "System Rescue CD" "systemrescuecd-x86*.iso" "http://sourceforge.net/projects/systemrescuecd/files/latest/download" "no" "http://www.sysresccd.org" "System Rescue CD"
  !insertmacro SetISOFileNames "Tails" "tails*.iso" "http://dl.amnesia.boum.org/tails/stable/" "no" "https://tails.boum.org/" "Tails" 
  !insertmacro SetISOFileNames "Terralinux" "Terra*.iso" "http://sourceforge.net/projects/terralinuxos/files/latest/download" "casper" "http://terralinux.blogspot.com/" "Terralinux"
  !insertmacro SetISOFileNames "TinyCore" "TinyCore-current.iso" "http://distro.ibiblio.org/pub/linux/distributions/tinycorelinux/4.x/x86/release/TinyCore-current.iso" "no" "http://tinycorelinux.com" "TinyCore"
  !insertmacro SetISOFileNames "Trisquel" "trisquel*.iso" "http://mirror.fsf.org/trisquel-images/" "casper" "http://trisquel.info/" "Trisquel"
  !insertmacro SetISOFileNames "Uberstudent" "uberstudent*.iso" "http://uberstudent.com/download" "casper" "http://uberstudent.org" "Uberstudent"
  ;Discontinued !insertmacro SetISOFileNames "Ubuntu Netbook Remix" "ubuntu-10.10-netbook-i386.iso" "http://mirror01.th.ifl.net/releases/maverick/ubuntu-10.10-netbook-i386.iso" "casper" "http://ubuntu.com" "Ubuntu"
  !insertmacro SetISOFileNames "Ubuntu Studio Installer" "ubuntustudio*.iso" "" "casper" "http://ubuntustudio.org" "Ubuntu Studio"
  !insertmacro SetISOFileNames "Ultimate Boot CD" "ubcd5*.iso" "http://ftp.cc.uoc.gr/mirrors/linux/ubcd/ubcd535.iso" "no" "http://www.ultimatebootcd.com" "UBCD"
  !insertmacro SetISOFileNames "Ultimate Edition" "ultimate-edition*.iso" "http://sourceforge.net/projects/ultimateedition/files/latest/download" "casper" "http://ultimateedition.info" "Ultimate Edition"
  !insertmacro SetISOFileNames "wattOS" "wattOS*.iso" "http://www.cpufu.com/iso/wattOS-R9-Microwatt32.iso" "no" "http://www.planetwatt.com/" "wattOS" 
  !insertmacro SetISOFileNames "XBMCbuntu" "xbmcbuntu*.iso" "http://ftp.df.lth.se/pub/xbmc/releases/XBMCbuntu/" "casper" "http://xbmc.org" "XBMC"
  !insertmacro SetISOFileNames "xPUD" "xpud-*.iso" "http://xpud.googlecode.com/files/xpud-0.9.2.iso" "no" "http://www.xpud.org" "xPud"
  !insertmacro SetISOFileNames "Zenwalk Live" "zen*.iso" "http://linuxfreedom.com/zenwalk/zenlive-6.4.iso" "no" "http://www.zenwalk.org" "Zenwalk "
;REVISIT  !insertmacro SetISOFileNames "ZeroShell" "ZeroShell*.iso" "http://na.mirror.garr.it/mirrors/zeroshell/ZeroShell-1.0.beta16.iso" "no" "http://www.zeroshell.net/" "ZeroShell"  
  !insertmacro SetISOFileNames "Zorin OS" "zorin*.iso" "http://zorinos.com/download.html" "casper" "http://zorin-os.com/index.html" "Zorin OS"  
;REVISIT !insertmacro SetISOFileNames "Chrome OS Lime" "ChromeOS-Lime*.zip" "http://chromeos.hexxeh.net/lime.php" "no" "http://chromeos.hexxeh.net/lime.php" "Chrome OS Lime"   
;REVISIT !insertmacro SetISOFileNames "Mandriva Free Installer" "mandriva-linux-free-dual-2010.iso" "http://www.gtlib.gatech.edu/pub/mandrake/official/iso/2010/mandriva-linux-free-dual-2010.iso" "no" "http://www.mandriva.com/en/downloads/" "Mandriva"	 

     !insertmacro SetISOFileNames "" "" "" "" "" ""
     !insertmacro SetISOFileNames "--- Live Antivirus Rescue CDs ---" "" "" "" "" ""
	 !insertmacro SetISOFileNames "" "" "" "" "" "" 
	 	 
  !insertmacro SetISOFileNames "Antivirus Live CD (Virus Scanner)" "AntivirusLiveCD*.iso" "http://sourceforge.net/projects/antiviruslivecd/files/latest/download" "no" "http://antiviruslivecd.4mlinux.com" "Antivirus Live CD"  	 
  !insertmacro SetISOFileNames "AOSS (Malware Scanner)" "AOSS.iso" "http://download.pctools.com/mirror/AOSS.iso" "no" "http://www.pctools.com/aoss/" "AOSS"
  !insertmacro SetISOFileNames "AVG Rescue CD" "avg_*.iso" "http://download.avg.com/filedir/inst/avg_arl_ffi_all_120_150814a10442.zip" "no" "http://www.avg.com/us-en/avg-rescue-cd" "AVG Rescue CD"
  !insertmacro SetISOFileNames "Avira Antivir Rescue Disk" "rescue-system.iso" "http://www.avira.com/en/download/product/avira-rescue-system" "no" "http://techblog.avira.com/2010/12/07/improved-avira-antivir-rescue-system/en/" "Avira"	 
  !insertmacro SetISOFileNames "Bitdefender Rescue CD" "bitdefender-rescue-cd.iso" "http://download.bitdefender.com/rescue_cd/bitdefender-rescue-cd.iso" "no" "http://www.bitdefender.com/support/How-to-create-a-Bitdefender-Rescue-CD-627.html" "Bitdefender"
  !insertmacro SetISOFileNames "Comodo Rescue Disk" "comodo_rescue_disk*.iso" "http://help.comodo.com/topic-170-1-493-5214-Downloading-Comodo-Rescue-Disk.html" "no" "http://help.comodo.com/topic-170-1-493-5208-Introduction-to-Comodo-Rescue-Disk.html" "Comodo"
  !insertmacro SetISOFileNames "Desinfec't 2013" "desinfect*.iso" "no" "" "" ""
  !insertmacro SetISOFileNames "DrWeb LiveCD" "drweb*.iso" "http://download.geo.drweb.com/pub/drweb/livedisk/drweb-livedisk-900-cd.iso" "no" "http://www.freedrweb.com/livecd/" "Dr Web"
  !insertmacro SetISOFileNames "ESET SysRescue Live" "eset*.iso" "http://www.eset.com/int/download/utilities/detail/family/239/#offline,151" "no" "http://kb.eset.com/esetkb/index?page=content&id=SOLN3509" "ESET SysRecue Live"   
  !insertmacro SetISOFileNames "F-Secure Rescue CD" "rescue-cd*.iso" "http://download.f-secure.com/estore/rescue-cd-3.16-52606.iso" "no" "http://www.f-secure.com/en/web/labs_global/removal/rescue-cd" "F-Secure Rescue CD"
  !insertmacro SetISOFileNames "G DATA Antivirus" "GD*.iso" "http://www.softpedia.com/get/Antivirus/G-Data-BootCD.shtml" "no" "http://www.gdatasoftware.com" "G Data"
  !insertmacro SetISOFileNames "Kaspersky Rescue Disk" "kav_rescue*.iso" "http://rescuedisk.kaspersky-labs.com/rescuedisk/updatable/kav_rescue_10.iso" "no" "http://support.kaspersky.com/viruses/rescuedisk" "Kaspersky Rescue Disk"	 
  !insertmacro SetISOFileNames "Panda Safe CD" "PandaSafeCD.iso" "http://www.pandasecurity.com/resources/sop/SafeCD/PandaSafeCD.iso" "no" "http://www.pandasecurity.com" "Panda Safe CD"
  !insertmacro SetISOFileNames "REMnux (Reverse Engineer Malware)" "remnux*.iso" "http://sourceforge.net/projects/remnux/files/version4/remnux-4.0-live-cd.iso/download" "no" "http://zeltser.com/remnux/" "REMnux"
  !insertmacro SetISOFileNames "Runtime Live CD" "runtimelivecd.iso" "http://www.runtime.org/runtimelivecd.iso" "no" "http://www.runtime.org/data-recovery-live-cd.htm" "Runtime Live CD"  
  !insertmacro SetISOFileNames "Trinity Rescue Kit" "trinity-rescue-kit.3.4*.iso" "http://mirror.tuxinator.org/trinityhome/trinity-rescue-kit.3.4-build-372.iso" "no" "http://trinityhome.org" "Trinity Rescue Kit"    

     !insertmacro SetISOFileNames "" "" "" "" "" "" 
     !insertmacro SetISOFileNames "--- Security and Penetration Testing ---" "" "" "" "" ""
	 !insertmacro SetISOFileNames "" "" "" "" "" "" 

  !insertmacro SetISOFileNames "BackBox" "backbox*.iso" "http://backbox.mirror.garr.it/mirrors/backbox/backbox-2.05-i386.iso" "no" "http://www.backbox.org/" "BackBox"  
  !insertmacro SetISOFileNames "CAINE Linux" "caine*.iso" "http://www.caine-live.net/page5/page5.html" "no" "http://www.caine-live.net/" "CAINE"    
  !insertmacro SetISOFileNames "Deft Linux" "deft*.iso" "http://www.deftlinux.net/download/" "no" "http://www.deftlinux.net" "Deft"  
  !insertmacro SetISOFileNames "Kali Linux" "Kali*.iso" "http://www.kali.org/downloads/" "no" "http://www.kali.org/" "Kali"	 
  !insertmacro SetISOFileNames "KNOPPIX" "*KNOPPIX*.iso" "http://www.knopper.net/knoppix-mirrors/index-en.html" "no" "http://knopper.net" "Knoppix"  
  !insertmacro SetISOFileNames "Parrot Security OS" "Parrot*.iso" "https://www.parrotsec.org/download/" "no" "https://www.parrotsec.org/" "Parrot"	
  !insertmacro SetISOFileNames "Pentoo" "Pentoo*.iso" "http://www.pentoo.ch/download/" "no" "http://www.pentoo.ch/about" "Parrot"	  
  !insertmacro SetISOFileNames "WifiSlax" "wifislax*.iso" "" "no" "http://www.wifislax.com" "WifiSlax"  
  !insertmacro SetISOFileNames "WifiWay" "WIFIWAY*.iso" "" "no" "http://www.wifiway.org" "WifiWay"    
  ; OBSOLETE !insertmacro SetISOFileNames "Backtrack" "BT*.iso" "http://mirror.switch.ch/ftp/pool/2/mirror/backtrack/BT5R3-GNOME-32.iso" "casper" "http://www.backtrack-linux.org" "Backtrack"
  
  
     !insertmacro SetISOFileNames "" "" "" "" "" "" 
     !insertmacro SetISOFileNames "--- Other or Non Linux Based Software ---" "" "" "" "" ""
	 !insertmacro SetISOFileNames "" "" "" "" "" "" 
	 
  !insertmacro SetISOFileNames "Hiren's Boot CD" "Hiren*.iso" "" "no" "" ""   
  !insertmacro SetISOFileNames "Falcon 4 Boot CD" "F4*.iso" "" "no" "" ""     
  !insertmacro SetISOFileNames "Kon-Boot FREE" "kon-boot*free.zip" "https://www.dropbox.com/s/f5i4g9vlmwoxrtp/kon-boot1.1-free.zip" "" "http://www.piotrbania.com/all/kon-boot/" "Kon-Boot" 
  !insertmacro SetISOFileNames "Kon-Boot Purchased" "kon-boot*.exe" "" "no" "http://www.piotrbania.com/all/kon-boot/" "Kon-Boot"  
  !insertmacro SetISOFileNames "Windows Vista Installer" "*.iso" "" "no" "" "" 
  !insertmacro SetISOFileNames "Windows 7 Installer" "*.iso" "" "no" "" "" 
  !insertmacro SetISOFileNames "Windows 8 Installer" "*.iso" "" "no" "" ""   
  !insertmacro SetISOFileNames "Windows 10 Installer" "*.iso" "" "no" "" ""     
	 
     !insertmacro SetISOFileNames "" "" "" "" "" ""
     !insertmacro SetISOFileNames "--- Try to use an Unsupported ISO ---" "" "" "" "" ""
	 !insertmacro SetISOFileNames "" "" "" "" "" ""  	 

  !insertmacro SetISOFileNames "Try Unlisted Linux ISO" "*.iso" "" "no" "" ""	   
FunctionEnd